---
- name: configuration
  hosts: all
  become: yes

  vars:
    mysql_root_password: "david"
    user1: "neme"
    user1pass: "nem"
    user2: "daniel"
    user2pass: "dan"

  tasks:
    - name: update apt package cache
      apt:
        update_cache: yes

    - name: install apache2
      apt:
        name: apache2
        state: present

    - name: start apache2
      service:
        name: apache2
        state: started

    - name: install mariadb
      apt:
        name: ["python3-pip", "python3-dev", "python3-mysqldb", "mariadb-server"]
        state: present
        update_cache: yes

    - name: start mariadb
      service:
        name: mariadb
        enabled: yes
        state: started

    - name: mariadb_root_password
      mysql_user:
        check_implicit_admin: yes
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        password: "{{ mysql_root_password }}"
        host: localhost

    - name: remove remote root
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        host: "{{ ansible_fqdn }}"
        state: absent

    - name: create database
      mysql_db:
        name: xerdocsdb
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: create new user1
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ user1 }}"
        password: "{{ user1pass }}"
        host: localhost
        priv: '*.*:ALL'

    - name: create new user2
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ user2 }}"
        password: "{{ user2pass }}"
        host: local host
        priv: '*.*:ALL'

    - name: install php libraries
      apt:
        name: ["php", "php-cli", "php-mysql", "php-xml", "php-mbstring", "php-curl", "php-gd", "php-zip", "php-json", "php-ldap", "php-imagick", "php-redis", "php-intl", "php-memcached", "php-soap", "php-ssh2", "php-bcmath", "libapache2-mod-php", "php-cgi", "php-xmlrpc", "php-xsl" ]
        state: present
        update_cache: yes

    - name: copy dir.conf
      copy:
        src: dir.conf
        dest: /etc/apache2/mods-enabled/dir.conf 

    - name: enable php module
      apache2_module:
        name: php
        state: present

    - name: change permission of /var/www/html
      become: yes
      become_user: root
      file:
        path: /var/www/html
        mode: 0777
        state: directory

    - name: create php script in /var/www/html
      copy:
        content: |
          <?php
          ech phpinfo();
          ?>
        dest: /var/www/html/info.php
        owner: root
        group: root
        mode: 0644

    - name: set ownership of /var/www/html
      become: yes
      become_user: root
      file:
        path: /var/www/html
        owner: root
        group: root
        state: directory

    - name: delete files in /var/www/html
      file:
        path: /var/www/html/
        state: absent

    - name: install git
      apt:
        name: git
        state: present

    - name: clone the xerdocsHMS repo
      git:
        repo: https://github.com/XerdocsNG/XerdocsHMS.git
        dest: /var/www/html/

    - name: checkout ui_ux branch
      git:
        repo: https://github.com/XerdocsNG/XerdocsHMS.git
        dest: /var/www/html
        version: ui_ux
        force: yes

    - name: copy files
      copy:
        src: /var/www/html/application/
        dest: /var/www/html/

    - name: delete database.php file
      file:
        path: /var/www/html/application/config/database.php
        state: absent

    - name: copy database.php file
      copy:
        src: database.php
        dest:  /var/www/html/application/config/database.php

    - name: restart apache
      service:
        name: apache2
        state: restarted
